- README.md
This PR is meant to address issue #1 by adding some additional information.
> Adding some help with installing RankLib jar to local maven repo

- src/main/java/com/o19s/es/ltr/query/LtrQuery.java
- src/main/java/com/o19s/es/ltr/query/LtrQueryBuilder.java
- Use ObjectParser to simplify parsing code
- Always build ArrayList with the expected size to reduce gc pressure
> Use ObjectParser and minor optimizations

- src/main/java/com/o19s/es/ltr/query/RankerQuery.java
- src/test/java/com/o19s/es/ltr/query/StoredLtrQueryBuilderTests.java
The tests were not really asserting something.
Assert that the resulting query is really what is stored in the model.
> Better StoredLtrQueryBuilderTests

- docs/rest_api.md
- src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java
- src/main/java/com/o19s/es/ltr/feature/store/index/Caches.java
- src/test/java/com/o19s/es/ltr/LtrTestUtils.java
- src/test/java/com/o19s/es/ltr/NodeSettingsIT.java
- src/test/java/com/o19s/es/ltr/action/BaseIntegrationTest.java
- src/test/java/com/o19s/es/ltr/feature/store/StoredFeatureSetParserTests.java
- src/test/java/com/o19s/es/ltr/feature/store/index/CachedFeatureStoreTests.java
- src/test/java/com/o19s/es/ltr/query/StoredLtrQueryIT.java
adds few node settings key to control the cache.
> Cache settings

- src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java
- src/test/java/com/o19s/es/ltr/logging/LoggingIT.java
> Add support for boosted queries in logging sub phase

- src/main/java/com/o19s/es/ltr/rest/RestCreateModelFromSet.java
- src/main/java/com/o19s/es/ltr/rest/RestSimpleFeatureStore.java
- src/test/resources/rest-api-spec/test/fstore/40_models.yaml
- src/test/resources/rest-api-spec/test/fstore/60_create_model_from_set.yaml
Indicate to the user that a model cannot be updated.
closes #77
> Better error message when trying to overwrite a model

- docs/building-features.rst
- docs/logging-features.rst
> [doc] feature queries should not be nested under a query block. Closes #102.

- docs/building-features.rst
- src/main/java/com/o19s/es/ltr/rest/RestSimpleFeatureStore.java
> Fixes #113 - Fix documentation and add handler on POST /_ltr/{store}

- docs/advanced-functionality.rst
- docs/building-features.rst
- src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java
- src/main/java/com/o19s/es/ltr/feature/store/StorableElement.java
- src/main/java/com/o19s/es/ltr/feature/store/StoredFeature.java
- src/main/java/com/o19s/es/ltr/feature/store/StoredFeatureSet.java
- src/main/java/com/o19s/es/ltr/feature/store/StoredLtrModel.java
- src/main/java/com/o19s/es/ltr/feature/store/index/IndexFeatureStore.java
- src/main/java/com/o19s/es/ltr/rest/RestSimpleFeatureStore.java
- src/test/java/com/o19s/es/ltr/feature/store/StoredFeatureParserTests.java
- src/test/java/com/o19s/es/ltr/feature/store/StoredFeatureSetParserTests.java
- src/test/java/com/o19s/es/ltr/feature/store/StoredLtrModelParserTests.java
- src/test/resources/rest-api-spec/test/fstore/20_features.yaml
- src/test/resources/rest-api-spec/test/fstore/30_featuresets.yaml
- src/test/resources/rest-api-spec/test/fstore/40_models.yaml
Inject the name found in the url part.
relates #113
> Make element name optional

- .gitignore
- build.gradle
- demo/README.md
- demo/collectFeatures.py
- demo/indexMlTmdb.py
- demo/loadFeatures.py
- demo/prepare_xpack.py
- demo/search.py
- demo/settings.cfg
- demo/train.py
- demo/utils.py
- docs/index.rst
- docs/x-pack.rst
- src/main/java/com/o19s/es/ltr/action/AddFeaturesToSetAction.java
- src/main/java/com/o19s/es/ltr/action/CachesStatsAction.java
- src/main/java/com/o19s/es/ltr/action/ClearCachesAction.java
- src/main/java/com/o19s/es/ltr/action/CreateModelFromSetAction.java
- src/main/java/com/o19s/es/ltr/action/FeatureStoreAction.java
- src/main/java/com/o19s/es/ltr/action/ListStoresAction.java
Backport the fix introduced in #126 to the 5.6.6 release branch.
> Backport X-Pack support fix to the support the 5.6.6 branch

- KNOWN_ISSUES.md
- README.md
Inform users about the cache issues and add a workaround.
closes #153
> Add a Known Issues section

- demo/indexMlTmdb.py
there are movie title other than english, so add encode to support multiple language.
> movie title encode to support multiple language

- demo/search.py
> Use correct model in demo search

- docs/index.rst
> change package name

- docs/building-features.rst
Added a short warning message regarding potential performance penalties associated with using script features
> Adds a warning regarding script feature performance - Issue #207

- README.md
As motivated by [1] and [2].
[1] https://github.com/o19s/elasticsearch-learning-to-rank/issues/211
[2] https://github.com/o19s/elasticsearch-learning-to-rank/pull/213
---
While here, thoughts on wrapping markdown, instead of very long lines?
> readme: add more information about updating plugin ES version

- src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java
- src/test/java/com/o19s/es/ltr/logging/LoggingIT.java
Fixed #226 for inner hits.
Modified the tests with nested documents/query with inner hits.
Added a new test. The new test will break without my change.
> Fix innert hit query for ltr log

- .travis.yml
- README.md
- circle.yml
Travis seems simpler for what we want (just run the dang tests) and seems to be working more consistently
> Fixes #229 Switch from Circle->Travis

- src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java
- src/test/java/com/o19s/es/ltr/logging/LoggingIT.java
We need the fix that has been merged in master for issue #227 backported to the ES 6.8 branch to unblock one of our use cases.
Tests are passing ✅.
> Backport: Fix inner hit query for ltr log

- docs/searching-with-your-model.rst
Removing comma that Elasticsearch complained about.
> Removing comma that Elasticsearch complained about.

- CONTRIBUTING.md
- README.md
@sstults  does this sound like it covers the learning curve you had to go up for developing the plugin? Am I missing anything glaring?
> Add guidelines for contributing to the plugin

- src/main/java/com/o19s/es/ltr/feature/Feature.java
- src/main/java/com/o19s/es/ltr/feature/FeatureSet.java
- src/main/java/com/o19s/es/ltr/feature/LtrModel.java
- src/main/java/com/o19s/es/ltr/feature/store/FeatureStore.java
- src/main/java/com/o19s/es/ltr/feature/store/OptimizedFeatureSet.java
- src/main/java/com/o19s/es/ltr/feature/store/StorableElement.java
- src/main/java/com/o19s/es/ltr/feature/store/StoredLtrModel.java
- src/main/java/com/o19s/es/ltr/feature/store/index/IndexFeatureStore.java
- src/main/java/com/o19s/es/ltr/query/LtrRewritableQuery.java
- src/main/java/com/o19s/es/ltr/query/LtrRewriteContext.java
- src/main/java/com/o19s/es/ltr/query/NoopScorer.java
- src/main/java/com/o19s/es/ltr/ranker/DenseLtrRanker.java
- src/main/java/com/o19s/es/ltr/ranker/LtrRanker.java
- src/main/java/com/o19s/es/ltr/ranker/parser/LtrRankerParser.java
- src/main/java/com/o19s/es/ltr/utils/Suppliers.java
> Fix javadoc annotations

- docs/feature-engineering.rst
- src/main/java/com/o19s/es/explore/ExplorerQuery.java
- src/main/java/com/o19s/es/explore/ExplorerScorer.java
- src/main/java/com/o19s/es/explore/PostingsExplorerQuery.java
- src/main/java/com/o19s/es/explore/StatisticsHelper.java
- src/test/java/com/o19s/es/explore/ExplorerQueryTests.java
> Add term position min, max and avg by documents

- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
Moved to gradle.properties, as seen in: https://github.com/spinscale/elasticsearch-ingest-opennlp
> Update to Elasticsearch 7.7.1

- build.gradle
- gradle.properties
- src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java
- src/main/java/com/o19s/es/ltr/action/TransportListStoresAction.java
- src/main/java/com/o19s/es/ltr/feature/store/index/IndexFeatureStore.java
- src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java
- src/main/java/com/o19s/es/ltr/rest/RestSimpleFeatureStore.java
- src/test/java/com/o19s/es/explore/ExplorerQueryBuilderTests.java
- src/test/java/com/o19s/es/ltr/action/BaseIntegrationTest.java
- src/test/java/com/o19s/es/ltr/logging/LoggingFetchSubPhaseTests.java
- src/test/java/com/o19s/es/ltr/query/LtrQueryBuilderTests.java
- src/test/java/com/o19s/es/ltr/query/StoredLtrQueryBuilderTests.java
- src/test/java/com/o19s/es/ltr/query/ValidatingLtrQueryBuilderTests.java
> Update to ES 7.8.0

- src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java
Hi, I just found a spelling mistake in the newest code. Please check this PR, Thanks.
>  fix the spelling mistakes.

- gradle.properties
version numbers only for once in a lifetime upgrade ease
> es7.9.1 version

- gradle.properties
> Version bump - es 7.9.3

- docs/building-features.rst
- docs/feature-engineering.rst
Fixing featureset delete URL in the docs.
> Fixing featureset delete URL in the docs

- build.gradle
- gradle.properties
replacing #372 with this just b/c when I pushed a small change it made a new branch instead of adding to Joris's original....
> Joris andrade joris/es 7 13 2

- gradle.properties
> 7.13.3 build

- src/main/java/com/o19s/es/ltr/rest/RestCreateModelFromSet.java
> Do not fail _createmodel with NPE when no content is provided

- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
Fix: https://github.com/o19s/elasticsearch-learning-to-rank/issues/421
> Update elasticsearch to 7.17.1

- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
* Update elasticsearch to 7.17.2
* Bump gradle version to 7.4.1
> Update elasticsearch to 7.17.2

- gradle.properties
Executed clean check as per CONTRIBUTING.md:
> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :compileJavaRestTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in …
> Version bump for es 7.17.5

- src/javaRestTest/java/com/o19s/es/ltr/action/BaseIntegrationTest.java
- src/main/java/com/o19s/es/ltr/feature/store/PrecompiledExpressionFeature.java
- src/main/java/com/o19s/es/ltr/query/DerivedExpressionQuery.java
- src/main/java/com/o19s/es/ltr/utils/Scripting.java
- src/main/java/com/o19s/es/termstat/TermStatQuery.java
- src/main/java/com/o19s/es/termstat/TermStatQueryBuilder.java
- src/main/java/com/o19s/es/termstat/TermStatScorer.java
- src/test/java/com/o19s/es/TestExpressionsPlugin.java
- src/test/java/com/o19s/es/ltr/ShardStatsIT.java
- src/test/java/com/o19s/es/ltr/logging/LoggingFetchSubPhaseTests.java
- src/test/java/com/o19s/es/termstat/TermStatQueryTests.java
Example conversion to using the new lang-expression facility in ES 8.5.0.
> Branch es 8.5 wrapped

- gradle.properties
fix: https://github.com/o19s/elasticsearch-learning-to-rank/issues/445
> Update elasticsearch to 8.5.1

- gradle.properties
fix: https://github.com/o19s/elasticsearch-learning-to-rank/issues/447
> Update elasticsearch to 8.5.2

- gradle.properties
- src/main/java/com/o19s/es/ltr/feature/store/PrecompiledTemplateFeature.java
- src/main/java/com/o19s/es/ltr/feature/store/index/Caches.java
- src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java
- src/test/java/com/o19s/es/ltr/feature/store/index/CachedFeatureStoreTests.java
- src/test/java/com/o19s/es/ltr/logging/LoggingFetchSubPhaseTests.java
Looks like there are quite a number of additional changes required again. :(
> Update elasticsearch to 8.6.0

- gradle.properties
Update ES Version.
This pull request updates dependency versions in the `gradle.properties` file to ensure compatibility and access to the latest features and fixes.
Dependency version updates:
* Updated `ltrVersion` from `1.5.11` to `1.5.12`.
* Updated `elasticsearchVersion` from `9.0.1` to `9.0.2`.
- https://www.elastic.co/docs/release-notes/elasticsearch#elasticsearch-9.0.2-release-notes
> update to ES version 9.0.2

- gradle.properties
Update ES Version.
This pull request updates the version numbers for dependencies in the `gradle.properties` file to ensure compatibility and access to the latest features and fixes.
Dependency updates:
* Updated `ltrVersion` from `1.5.11` to `1.5.13`.
* Updated `elasticsearchVersion` from `9.0.1` to `9.0.3`.
- https://www.elastic.co/docs/release-notes/elasticsearch#elasticsearch-9.0.3-release-notes
> update to ES version 9.0.3
