- src/main/java/com/o19s/es/ltr/query/LtrQuery.java
- src/test/java/com/o19s/es/ltr/query/LtrQueryTests.java
Some queries exist only to implement `rewrite` and return another query. In and of themselves they do not implement the needed functionality to be a  fully fledged query. This PR ensures that the ritual of calling rewrite before using a query is followed.
(most of the changes are restructuring tests to try with a different blend of features)
> Rewritten queries bug

- src/main/java/com/o19s/es/ltr/query/LtrQuery.java
- src/main/java/com/o19s/es/ltr/query/NoopScorer.java
- src/test/java/com/o19s/es/ltr/query/LtrQueryTests.java
Sometimes leaf IndexReaders don't include a term, so there's no scorer returned by the weight. This PR takes care this case by injecting a NoopScorer when null is returned. (test included)
> Features not computed for missing terms

- README.md
- build.gradle
- src/main/java/com/o19s/es/ltr/query/NoopScorer.java
Depend on [RankLibPlus](http://github.com/o19s/ranklibplus) instead of Ranklib. This resolves a nasty performance problem when loading models due to slow deserialization of LambdaMART models in RankLib.
> Use ranklib plus

- src/main/java/com/o19s/es/ltr/feature/Feature.java
- src/main/java/com/o19s/es/ltr/feature/FeatureSet.java
- src/main/java/com/o19s/es/ltr/feature/PrebuiltFeature.java
- src/main/java/com/o19s/es/ltr/feature/PrebuiltFeatureSet.java
- src/main/java/com/o19s/es/ltr/query/LtrQueryBuilder.java
- src/main/java/com/o19s/es/ltr/query/RankerQuery.java
- src/test/java/com/o19s/es/ltr/query/LtrQueryBuilderTests.java
It was missed but is needed by some queries because they'll fail
if they are not rewritten.
This changes my mind concerning the model I'm not sure now
that it's reasonable to consider that FeatureSet.toQueries()
will accept a QueryShardContext and a map of params, it's likely
that templating will happen before.
> LtrQueryBuilder should support the rewrite step

- src/test/java/com/o19s/es/ltr/query/LtrQueryBuilderTests.java
The test was simply wrong: adding a TermsQueryBuilder feature with "feat" but asserting
it was "1st feat", now we test that we receive the same TermsQueryBuilder
> Fix rewrite test of the LTR query builder

- demo/judgments.py
The one-pass parsing of `sample_judgements.txt` skips the first judgement. Indeed, the function `_queriesFromHeader` breaks when it meets the first line not beginning with `#`. When the file handler is passed to `_judgmentsFromBody`, the first judgement is inevitably skipped. While it is possible to solve the problem by adding a blank line between the header and the body, the two-pass version is less error-prone.
> Fix the problem of parsing sample_judgements.txt in the demo

- src/main/java/com/o19s/es/ltr/ranker/dectree/NaiveAdditiveDecisionTree.java
- src/test/java/com/o19s/es/ltr/ranker/dectree/NaiveAdditiveDecisionTreeTests.java
- src/test/resources/com/o19s/es/ltr/ranker/dectree/simple_tree.txt
The split threshold was always compared to the feature value of the
root split.
Sadly the test was written in a way that did not catch the issue.
Fix the tests and the implementation.
> Fix NaiveAdditiveDecisionTree

- docs/logging.md
- src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java
- src/main/java/com/o19s/es/ltr/feature/store/CompiledLtrModel.java
- src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java
- src/main/java/com/o19s/es/ltr/logging/LoggingSearchExtBuilder.java
- src/main/java/com/o19s/es/ltr/query/NoopScorer.java
- src/main/java/com/o19s/es/ltr/query/RankerQuery.java
- src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java
- src/main/java/com/o19s/es/ltr/ranker/LogLtrRanker.java
- src/main/java/com/o19s/es/ltr/ranker/NullRanker.java
- src/main/java/com/o19s/es/ltr/ranker/linear/LinearRanker.java
- src/test/java/com/o19s/es/ltr/logging/LoggingFetchSubPhaseTests.java
- src/test/java/com/o19s/es/ltr/logging/LoggingIT.java
- src/test/java/com/o19s/es/ltr/logging/LoggingSearchExtBuilderTests.java
- src/test/java/com/o19s/es/ltr/query/LtrQueryTests.java
- src/test/java/com/o19s/es/ltr/query/StoredLtrQueryBuilderTests.java
- src/test/java/com/o19s/es/ltr/ranker/LogLtrRankerTests.java
- src/test/java/com/o19s/es/ltr/ranker/parser/LinearRankerParserTests.java
Use the search_ext to tell the plugin which model/featureset to collect.
Feature values are extracted as part of the search response using a
special field _ltrlog.
Multiple models/sets can be collected at once.
Feature collection happens during the fetch phase by running the feature
queries on the hits returned.
Queries to log are identified by using the _name attribute when used inside
the main search query or by an index in the list of rescore queries
For users that can afford running the feature queries a second time on the
returned hits this should permit to do runtime logging.
fixes #13
> Add feature logging

- src/main/java/com/o19s/es/explore/ExplorerQuery.java
- src/test/java/com/o19s/es/explore/ExplorerQueryTests.java
It prevents outputing the constant score for docs that do not match the nested
query.
> Don't use subWeights when scoring collection scoped stats

- src/main/java/com/o19s/es/ltr/feature/store/StoredFeatureSet.java
- src/test/java/com/o19s/es/ltr/feature/store/StoredFeatureSetParserTests.java
This was forbidden for no particular reason except than using an empty featureset
makes no sense. But if creating an empty set makes sense in certain usecases
let's allow them.
closes #82
> Allow empty featuresets

- src/test/java/com/o19s/es/ltr/feature/store/index/CachedFeatureStoreTests.java
They randomly fail, the code itself is being covered by elastic itself.
It should not be big deal to disable them while we find a proper fix
to make them stable.
relates #75
> Mark 2 CachedFeatureStoreTests tests as @BadApple

- docs/rest_api.md
- src/main/java/com/o19s/es/ltr/action/AddFeaturesToSetAction.java
- src/main/java/com/o19s/es/ltr/action/TransportAddFeatureToSetAction.java
- src/main/java/com/o19s/es/ltr/feature/store/StoredFeatureSet.java
- src/main/java/com/o19s/es/ltr/rest/RestAddFeatureToSet.java
- src/test/java/com/o19s/es/ltr/LtrTestUtils.java
- src/test/java/com/o19s/es/ltr/action/AddFeaturesToSetActionIT.java
- src/test/java/com/o19s/es/ltr/feature/store/StoredFeatureParserTests.java
- src/test/java/com/o19s/es/ltr/feature/store/StoredFeatureSetTests.java
- src/test/java/com/o19s/es/ltr/rest/FeaturesParserTests.java
- src/test/resources/rest-api-spec/api/ltr.add_features_to_set.json
- src/test/resources/rest-api-spec/test/fstore/50_add_features_to_set.yaml
Allows to update featureset by adding features in the request body
rather than providing a prefix query.
Initially it was only possible to update the featureset by adding
features from the store.
It's now possible to provide the feature definitions directly in
the request body bypassing the feature store.
Added an option to merge the features, it permits to replace a
feature instead of throwing an error.
relates #83
> Update featureset with features provided in request body

- demo/collectFeatures.py
- docs/logging.md
- src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java
- src/test/java/com/o19s/es/ltr/logging/LoggingFetchSubPhaseTests.java
- src/test/java/com/o19s/es/ltr/logging/LoggingIT.java
Change the dictionary logging structure to a list. This ensures you can use the ordinal when logging for tools like ranklib that want that info. 
Example:
```
"fields": {
"_ltrlog": [
{
"log_entry1": [
{
"name": "body_query",
"value": 9.8376875
},
{
"name": "title_query",
"value": 12.318446
}
]
}
]
```
When no value present (and `missing_as_zero` is `false`) then feature is logged with "value" key missing, ie:
```
"fields": {
"_ltrlog": [
{
"log_entry1": [
{
"name": "body_query"
},
{
"name": "title_query",
"value": 12.318446
}
]
}
]
```
> Fixes #85 -- logs features as a list

- src/main/java/com/o19s/es/ltr/rest/RestSimpleFeatureStore.java
- src/test/resources/rest-api-spec/api/ltr.get_store.json
- src/test/resources/rest-api-spec/test/fstore/10_manage.yaml
Add a new GET endpoint to test if the store exists.
Only works for custom stores as GET /_ltr is already bound
to the list store action.
closes #67
> Returns a 404 when issuing a GET on a missing store

- docs/rest_api.md
- src/main/java/com/o19s/es/ltr/action/TransportFeatureStoreAction.java
- src/main/java/com/o19s/es/ltr/feature/store/index/IndexFeatureStore.java
- src/main/java/com/o19s/es/ltr/rest/RestSimpleFeatureStore.java
- src/test/resources/rest-api-spec/api/ltr.clear_cache.json
- src/test/resources/rest-api-spec/test/fstore/10_manage.yaml
Names based on feature, featureset and model are forbidden.
Make sure that the store name is a valid index name as well.
closes #80
> Prevent creating feature stores with ambiguous names

- src/main/java/com/o19s/es/ltr/action/TransportFeatureStoreAction.java
The sltr query being unfiltered using a validation block with a large index can
be very slow. Use terminate_after to make sure we don't score all the docs in
the index.
> Don't validate the whole index

- src/test/resources/rest-api-spec/test/fstore/10_manage.yaml
quick fix to avoid isolation problems between tests.
Would be better to integrate this cleanup more appropriately.
> [tests] Cleanup the cache before checking it

- src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java
- src/main/java/com/o19s/es/ltr/rest/RestSimpleFeatureStore.java
- src/test/resources/rest-api-spec/test/fstore/10_manage.yaml
The cache was only properly maintained on UPDATE actions.
Add proper cache invalidation on:
- store deletion
- model/set/feature deletion
We still do not maintain the cache properly if the user attempts to change
the store content directly bypassing our rest endpoints (creating model
using the elasticsearch index API).
Fixes #118
> Fixes #118 properly handle cache state on store and model deletion

- .gitignore
- build.gradle
- demo/README.md
- demo/collectFeatures.py
- demo/indexMlTmdb.py
- demo/loadFeatures.py
- demo/prepare_xpack.py
- demo/search.py
- demo/settings.cfg
- demo/train.py
- demo/utils.py
- docs/index.rst
- docs/x-pack.rst
- src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java
- src/main/java/com/o19s/es/ltr/action/AddFeaturesToSetAction.java
- src/main/java/com/o19s/es/ltr/action/CachesStatsAction.java
- src/main/java/com/o19s/es/ltr/action/ClearCachesAction.java
- src/main/java/com/o19s/es/ltr/action/CreateModelFromSetAction.java
- src/main/java/com/o19s/es/ltr/action/FeatureStoreAction.java
- src/main/java/com/o19s/es/ltr/action/ListStoresAction.java
This is a follow-up PR growing on the basis of the great work created in #125.
* X Pack only allows our custom transport actions if we name them such
that they live inside the cluster management namespace. Rename them
all.
* Adjusted demo to support xpack. A support script creates
appropriate admin and user roles then creates an ltr admin user. The
rest of the scripts are adjusted to consistently use the host and
username from settings.cfg.
* Adjust documentation to include the need to setup the x-pack roles if under that use case.
Fixes #116
> X-Pack support

- demo/collectFeatures.py
- docs/logging-features.rst
in some examples we use a must clause while we really
want to filter. This can cause confusions about how
the plugin handles feature values.
closes #148
> [doc] Use filter instead of must to avoid confusion

- src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java
- src/main/java/com/o19s/es/ltr/logging/LtrLoggingException.java
- src/test/java/com/o19s/es/ltr/logging/LoggingFetchSubPhaseTests.java
It can be extremely misleading to allow logging NaN as it creates
a log entry missing:false, value:NaN.
We should detect this behavior as soon as possible to warn the user
that their query is broken.
fixes #136
> Fail when logging NaN values

- docs/building-features.rst
- docs/searching-with-your-model.rst
- src/main/java/com/o19s/es/ltr/feature/store/PrecompiledExpressionFeature.java
- src/main/java/com/o19s/es/ltr/query/DerivedExpressionQuery.java
- src/test/java/com/o19s/es/ltr/feature/store/StoredFeatureSetParserTests.java
- src/test/java/com/o19s/es/ltr/query/StoredLtrQueryIT.java
`derived_expression` did not allow for passing in query time variables. This change allows `derived_expression` to pass in query time parameters (only type:double) as `variables` in lucene expression. 
I simply reuse the existing `DerviedExpressionQuery` and modify the `getDoubleValuesSource` to emit a `DoubleValuesSource` if it happens to be a `queryParam`.
Example use case: We have one _mustached_feature_: `distance` and one _derived_feature_: `distance_with_some_multiplier` as follows
```
"features": [
{
"name": "distance",
"params": [
"distance_latitude",
"distance_longitude"
],
"template_language": "mustache",
"template": {
"function_score": {
"script_score": {
"script": {
"lang": "native",
"source": "feature_extractor",
"params": {
"name": "distance",
"type": "distance",
"latitude": …
```
> Add support for query time `variables` in `derived_expression`.

- build.gradle
- circle.yml
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/com/o19s/es/ltr/feature/store/PrecompiledTemplateFeature.java
- src/main/java/com/o19s/es/ltr/feature/store/StoredFeature.java
- src/main/java/com/o19s/es/ltr/feature/store/StoredLtrModel.java
- src/main/java/com/o19s/es/ltr/feature/store/index/IndexFeatureStore.java
- src/main/java/com/o19s/es/ltr/ranker/parser/LinearRankerParser.java
- src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostJsonParser.java
- src/main/java/com/o19s/es/ltr/rest/RestSimpleFeatureStore.java
- src/main/java/com/o19s/es/template/mustache/CustomMustacheFactory.java
- src/main/java/com/o19s/es/template/mustache/MustacheUtils.java
- src/test/java/com/o19s/es/ltr/LtrTestUtils.java
- src/test/java/com/o19s/es/ltr/feature/store/StoredFeatureParserTests.java
- src/test/java/com/o19s/es/ltr/feature/store/StoredFeatureSetParserTests.java
- src/test/java/com/o19s/es/ltr/feature/store/StoredLtrModelParserTests.java
- src/test/java/com/o19s/es/ltr/feature/store/index/IndexFeatureStoreTests.java
- src/test/java/com/o19s/es/ltr/logging/LoggingSearchExtBuilderTests.java
- src/test/java/com/o19s/es/ltr/query/StoredLtrQueryBuilderTests.java
- src/test/java/com/o19s/es/ltr/ranker/parser/LinearRankerParserTests.java
- src/test/java/com/o19s/es/ltr/ranker/parser/XGBoostJsonParserTests.java
- src/test/java/com/o19s/es/ltr/rest/FeaturesParserTests.java
> Elastic 6.3.0 support; closes #168

- docs/building-features.rst
- src/main/java/com/o19s/es/ltr/feature/store/FeatureSupplier.java
- src/main/java/com/o19s/es/ltr/feature/store/ScriptFeature.java
- src/main/java/com/o19s/es/ltr/feature/store/StoredFeature.java
- src/main/java/com/o19s/es/ltr/ranker/DenseFeatureVector.java
- src/main/java/com/o19s/es/ltr/ranker/LtrRanker.java
- src/main/java/com/o19s/es/ltr/ranker/ranklib/DenseProgramaticDataPoint.java
- src/main/java/com/o19s/es/ltr/rest/RestSimpleFeatureStore.java
- src/test/java/com/o19s/es/ltr/action/BaseIntegrationTest.java
- src/test/java/com/o19s/es/ltr/feature/store/FeatureSupplierTests.java
- src/test/java/com/o19s/es/ltr/query/StoredLtrQueryIT.java
@nomoa thanks for the POC!
I added some wiring code on top of your [poc: d629523  ](https://github.com/nomoa/elasticsearch-learning-to-rank/commit/d629523d5d29f60a45c7dd5f7ede5844430c84ea) to get this code working end to end.
Maybe I am missing something but although this seems to work, in its current form the native java plugins still seem to have have a compile time dependency on LTR  and need to access the `FeatureVector` with something like:
`((ScriptFeature.SupplierSupplier)queryParams.get("feature_vector")).get().getFeatureScore(0)`
We can make this simpler and use `featureName` like
`((ScriptFeature.SupplierSupplier)queryParams.getFeatureScore(featureName)`
but the native java code still seems to depend on `SupplierSupplier` class from LTR. 
Is there a way we could avoid and this …
> poc add derived feature support in native plugins. reuses poc from sha: d629523

- src/main/java/com/o19s/es/ltr/query/RankerQuery.java
We saw this code to be the bottleneck in our tests. Turns out when we use a lot of features/scorers and recall a large amount the `advanceSubIterators` loop becomes the hotspot. I use Lucene's DisiPriorityQueue for this purpose. Initial tests showed us that this hotspot is now removed for us.
@nomoa @softwaredoug  please let me know what you think.
Hotspot Before fix:
> Use DisiPriorityQueue for advancing subIterators instead of looping over all

- src/main/java/com/o19s/es/ltr/query/RankerQuery.java
We were seeing `concurrent modifcation exceptions` on `RankerQuery` while stress testing ltr plugin with concurrent queries.  StackTrace: https://gist.github.com/umeshdangat/834e5d8b840d4c81c14921d58967ea93
@nomoa helped understand the underlying issue and it is documented here in the slack chat: 
https://gist.github.com/umeshdangat/b02e7333513b230d3c2e734e5954a42a
We deployed this fix in our stress test environment and the issue seems to be resolved.
Essentially caching `LtrScript`  in the current form uses FeatureSupplier in its `equals` method which can mutate (due to feature vector) and hence is not cacheable.
> turn off caching for RankerQuery

- build.gradle
Similar commit to what it was done [here](https://github.com/o19s/elasticsearch-learning-to-rank/commit/3075d1cd015c2b5e9f4c24c069bca75674687879) for upgrading to 6.5.2
We are starting to use the plugin and planning to install it during the next upgrade of our production clusters.
Thank you for developing this plugin :)
> Upgrade elasticsearch to 6.5.4

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java
- src/main/java/com/o19s/es/ltr/ranker/ranklib/RankLibScriptEngine.java
- src/test/java/com/o19s/es/ltr/query/ValidatingLtrQueryBuilderTests.java
This is a naive attempt at upgrading the plugin to ES version 6.6.0
The changes are minimal, but I'm curious what opinions are on the removal of an `@Override`, and the removal of settings in `super`. The latter seems especially suspicious of being wrong.
Is there anything obvious going wrong here?
It appears, too, that after running the tests I see:
```
> Task :compileTestJava
Note: /home/ubuntu/diffeo/images/elasticsearch/elasticsearch-learning-to-rank/src/test/java/com/o19s/es/explore/ExplorerQueryTests.java uses or overrides a deprecated API.
```
and occassionally
```
> Task :integTestRunner
==> Test Info: seed=3D974279FB1A303; jvm=1; suites=7
Exception thrown by subscriber method onHeartbeat(com.carrotsearch.ant.tasks.junit4.events.aggregated.HeartBeatEvent) on subscriber …
```
> Update ES version to 6.6.0

- src/main/java/com/o19s/es/explore/ExplorerQueryBuilder.java
- src/main/java/com/o19s/es/ltr/query/LtrQueryBuilder.java
- src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java
- src/main/java/com/o19s/es/ltr/query/ValidatingLtrQueryBuilder.java
- src/main/java/com/o19s/es/ltr/utils/AbstractQueryBuilderUtils.java
As the method is now open to subclasses based on the pull request
https://github.com/elastic/elasticsearch/issues/27865, we can now
use the method from the parent class.
> Remove declareStandardFields method from AbstractQueryBuilderUtils

- src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java
- src/test/java/com/o19s/es/ltr/logging/LoggingIT.java
We need the fix for issue [#227](https://github.com/o19s/elasticsearch-learning-to-rank/issues/226) backported to the ES 6.3.1 branch to unblock one of our use cases.
The fix applied cleanly and the tests pass.
> Backport: Fix innert hit query for ltr log (#227)

- build.gradle
- src/main/java/com/o19s/es/ltr/feature/store/ScriptFeature.java
- src/test/java/com/o19s/es/explore/ExplorerQueryBuilderTests.java
- src/test/java/com/o19s/es/ltr/action/BaseIntegrationTest.java
- src/test/java/com/o19s/es/ltr/query/LtrQueryBuilderTests.java
- src/test/java/com/o19s/es/ltr/query/StoredLtrQueryBuilderTests.java
- src/test/java/com/o19s/es/ltr/query/ValidatingLtrQueryBuilderTests.java
Upgrading plugin to Elasticsearch 7.5.0
Related Elastic changes/issues for reference:
- [Building ES plugin for 7.5.0 fails](https://github.com/elastic/elasticsearch/issues/49787)
- [Replace SearchContext -> QueryShardContext](https://github.com/elastic/elasticsearch/commit/4414fccb2765dd24895216636e68aabea2d156ca)
> Elastic LTR 7.5.0 port, Fixes #260

- docs/advanced-functionality.rst
- src/main/java/com/o19s/es/ltr/feature/store/ExtraLoggingSupplier.java
- src/main/java/com/o19s/es/ltr/feature/store/ScriptFeature.java
- src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java
- src/main/java/com/o19s/es/ltr/query/DerivedExpressionQuery.java
- src/main/java/com/o19s/es/ltr/query/LtrRewritableQuery.java
- src/main/java/com/o19s/es/ltr/query/LtrRewriteContext.java
- src/main/java/com/o19s/es/ltr/query/RankerQuery.java
- src/main/java/com/o19s/es/ltr/ranker/LogLtrRanker.java
- src/test/java/com/o19s/es/ltr/action/BaseIntegrationTest.java
- src/test/java/com/o19s/es/ltr/feature/store/ExtraLoggingSupplierTests.java
- src/test/java/com/o19s/es/ltr/logging/LoggingIT.java
We have had some inconvenience with using logging and our native scripts. For some of our feature extractors, we care about not only the final feature value, but also some 'base' feature(s) used/generated during the computation.
Currently, it would be possible to create an LTR feature for each of these 'base' features, then derive the true feature needed for model evaluation. However, this does not work for all of our uses because:
1) We cannot efficiently cache doc value lookups/intermediate computations across features
2) The 'base' features are not necessarily numeric
3) The Scorer interface requires that all these 'base' features be non-negative, which can be challenging
This branch is an attempt to mitigate some of these issues by allowing native scripts to add arbitrary logging …
> Add optional extra logging for native scripts

- src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java
- src/main/java/com/o19s/es/ltr/feature/store/index/IndexFeatureStore.java
- src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java
- src/main/java/com/o19s/es/ltr/utils/FeatureStoreLoader.java
- src/test/java/com/o19s/es/ltr/action/BaseIntegrationTest.java
- src/test/java/com/o19s/es/ltr/query/StoredLtrQueryBuilderTests.java
As reported by this issue: #269.
Today the plugin is not using the [shard request cache](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html#shard-request-cache) due to this method call `context.getClient()` on `StoredLtrQueryBuilder` class which makes the Elasticsearch set the request as non-cacheable.
This PR proposes to avoid calling this method on every request so ElasticSearch can cache requisitions.
After simulating some load-tests, we have the following results:
- Plugin not using shard request cache:
- Plugin using shard request cache:
Those tests ran against different types of queries, rescoring 5000 documents using an XGboost model. Analyzing the results we can see an improvement of 40% on throughput.
> Closes #269 - Enabling shard request cache

- build.gradle
- src/main/java/com/o19s/es/ltr/ranker/ranklib/RankLibScriptEngine.java
Makes the plugin compatible with ES 7.6.1
> Compatibility with ES v7.6.1

- docs/feature-engineering.rst
- src/main/java/com/o19s/es/explore/ExplorerQuery.java
- src/main/java/com/o19s/es/explore/ExplorerScorer.java
- src/test/java/com/o19s/es/explore/ExplorerQueryTests.java
Refer: #155 
When you create some feature using the `raw_tf` sometimes when term does not exist in a document we have a null pointer exception. Example:
```
POST _ltr/_featureset/some_cool_features
{
"featureset": {
"name": "some_cool_features",
"features": [
{
"name": "sum_raw_tf_text",
"params": [
"keywords"
],
"template_language": "mustache",
"template": {
"match_explorer": {
"type": "sum_raw_tf",
"query": {
"match": {
"text": "{{keywords}}"
}
}
}
}
}
]
}
}
curl -H 'content-type:application/json' -X POST http://localhost:9200/*_ltr/_search -d '{
"_source": ["_ltrlog.main"],
"query": {
"bool": {
"filter": [
{
"terms": {
"_id": [
"165241254"
]
}
}
],
"should": [
{
"sltr": {
"_name": "some_cool_features",
"featureset": "some_cool_features",
"params": {
"keywords": …
```
> Fix raw_tf in match_explorer

- docs/advanced-functionality.rst
- src/main/java/com/o19s/es/explore/StatisticsHelper.java
- src/main/java/com/o19s/es/ltr/feature/store/ScriptFeature.java
- src/main/java/com/o19s/es/termstat/TermStatScorer.java
- src/main/java/com/o19s/es/termstat/TermStatSupplier.java
- src/test/java/com/o19s/es/ltr/action/BaseIntegrationTest.java
- src/test/java/com/o19s/es/ltr/logging/LoggingIT.java
- src/test/java/com/o19s/es/termstat/TermStatQueryTests.java
The term statistic injection functionality on ScriptFeatures wasn't very friendly towards query time parameters. This update will check the query parameters as a fallback if nothing is set in the script parameters.
> Add support for query time parameters for ScriptFeature term statistics

- docs/index.rst
The demo has moved to hello-ltr.
It was updated in README.md but not here.
> update demo link to hello-ltr

- .github/workflows/release.yml
- build.gradle
- publish/build.gradle
- settings.gradle
Added gradle script for deploying to maven central repo on Release with GitHub Actions.
Need to 
* Create account on sonatype and add url, username, password to GitHub secrets as name below
* SONATYPE_REPO_URL
* SONATYPE_USER
* SONATYPE_PASS
* Create GPG Key and add key, password to GitHub secrets as name below
* GPG_SIGNING_KEY
* GPG_SIGNING_PASS
To test locally, 
1. Set SONATYPE_REPO_URL to `file://path/to/output/'
1. comment out credentials clause at publish/build.gradle
1. Generate GPG key and set GPG_SIGNING_KEY, GPG_SIGNING_PASS
1. run `./gradlew publish`
https://github.com/o19s/elasticsearch-learning-to-rank/issues/298
I checked scripts work correctly except uploading process. (I couldn't create account on sonatype... sorry) But other process seems to be ok. Result pom will be like …
> Add gradle scripts to upload plugin to maven central

- src/main/java/com/o19s/es/ltr/feature/store/index/IndexFeatureStore.java
NPE is currently thrown where referencing a featureset.
Throw IAE with a meaningful error message instead.
> Better error handling when fetching feature/featuresets

- publish/build.gradle
#350 
Fixed build script to include all classes into jar. Present script is made as subproject, which doesn't contain main project's script.
To see result jar is containing classes properly, 
* run `gradle publishLtrPublicationToMavenLocal`
* go `~/.m2/repository/com/o19s/ltr/....` and chose generated jar, unzip it. Then you can find all the classes are contained in the jar.
> Bugfix: change target component to publish

- src/javaRestTest/java/com/o19s/es/ltr/logging/LoggingIT.java
- src/main/java/com/o19s/es/ltr/logging/LoggingFetchSubPhase.java
- src/main/java/com/o19s/es/ltr/utils/Suppliers.java
- src/test/java/com/o19s/es/ltr/logging/LoggingFetchSubPhaseTests.java
Do not log nested hits.
Since there does not seem to be a way to know from FetchContext that we're running on the nested hits we have to delay the construction of the query weight and logging consumers after we read the first hit.
It'd be great if FetchContext provide some hints to know in which contect the the fetch processor is going to be applied.
fixes #357
> Fix rescore nested hits

- build.gradle
Importing the build.gradle into intellij has some oddities around the publish and rest-api-spec subprojects.  Because the build.gradle says allprojects have the dependencies they also need the repos to be happy.
> Fix IDEA build

- docs/advanced-functionality.rst
- docs/building-features.rst
Update `building-features.rst` by adding quotes around mustache variables for geo_distance example.
Add missing commas in examples in `advanced-functionality.rst`
> Fix minor syntax errors in docs examples

- src/main/java/com/o19s/es/ltr/logging/LoggingSearchExtBuilder.java
- src/test/java/com/o19s/es/ltr/logging/LoggingSearchExtBuilderTests.java
this PR solves the following exception, thrown when trying to build the Ext property for ES
```
org.elasticsearch.ElasticsearchException: com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name (context: Object)
Caused by: com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name (context: Object)
[..]
at com.o19s.es.ltr.logging.LoggingSearchExtBuilder.toXContent(LoggingSearchExtBuilder.java:80) ~[elasticsearch-learning-to-rank-1.5.7-es7.13.4.jar:1.5.7-es7.13.4]
[..]
```
The current fix I used in one of my projects is to create a new class:
```java
import java.io.IOException;
import org.elasticsearch.common.xcontent.XContentBuilder;
/**
* The original implementation is affected by a bug, and it is building …
```
> Fix exception in LoggingSearchExtBuilder JSON

- docs/advanced-functionality.rst
- src/javaRestTest/java/com/o19s/es/ltr/logging/LoggingIT.java
- src/main/java/com/o19s/es/ltr/query/RankerQuery.java
- src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java
- src/main/java/com/o19s/es/ltr/query/ValidatingLtrQueryBuilder.java
Hi, I would like to share a simple idea for improving efficiency of feature score logging.
The idea is to cache feature scores at model execution and use them at feature score logging.
We have developed this patch based on the idea, and
in our development environment, this patch significantly reduced average latency without changing the results.
What do you think about merging this patch? Thanks.
Usage of this patch: Set `"cache": true` option to a `sltr` query which is the target of feature score logging.
```diff
"sltr": {
"model": "...",
+            "cache": true,
"params": { 
...
```
> Feature Score Caching for Efficient Feature Score Logging

- gradle.properties
ES 7.17.3 is out:
```
{
"name" : "...",
"cluster_name" : "....",
"cluster_uuid" : "NThobugSQR-qRPGkFr_tVw",
"version" : {
"number" : "7.17.3",
"build_flavor" : "default",
"build_type" : "docker",
"build_hash" : "5ad023604c8d7416c9eb6c0eadb62b14e766caff",
"build_date" : "2022-04-19T08:11:19.070913226Z",
"build_snapshot" : false,
"lucene_version" : "8.11.1",
"minimum_wire_compatibility_version" : "6.8.0",
"minimum_index_compatibility_version" : "6.0.0-beta1"
},
"tagline" : "You Know, for Search"
}
```
This builds the plugin against it.
> bump ES version to 7.17.3

- gradle.properties
According to the release note of elasticsearch 8.5.3 lucene got an upgrade in it: https://www.elastic.co/guide/en/elasticsearch/reference/8.5/release-notes-8.5.3.html.
> Update elasticsearch to 8.5.3 and lucene to 9.4.2

- gradle.properties
- src/main/java/com/o19s/es/explore/ExplorerQueryBuilder.java
- src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java
- src/main/java/com/o19s/es/ltr/feature/store/StoredLtrModel.java
- src/main/java/com/o19s/es/ltr/query/LtrQueryBuilder.java
- src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java
- src/main/java/com/o19s/es/ltr/query/ValidatingLtrQueryBuilder.java
- src/main/java/com/o19s/es/termstat/TermStatQueryBuilder.java
- src/test/java/com/o19s/es/ltr/feature/store/StoredLtrModelParserTests.java
According to the release notes of elasticsearch 8.7.0 lucene got an upgrade in it: https://www.elastic.co/guide/en/elasticsearch/reference/8.7/release-notes-8.7.0.html.
> Update elasticsearch to 8.7.0 and lucene to 9.5.0

- gradle.properties
Hi,
Latest version of ES **7.x** is `7.17.19`.
This PR is made for releasing this version.
I don't know if this PR is appropriate, given the conflict with master that support ES 8.x.
I checked out latest 7.x from the history, and incremented the version in gradle.properties.
Test are passing.
> Update elasticsearch 7.x from 7.17.17 to 7.17.19

- gradle.properties
Bump latest version of ES **7.x** to 7.17.10.
@nathancday Thanks for the release of last time (es 7.17.9) :+1:
> Update elasticsearch 7.x to 7.17.10

- docs/training-models.rst
- src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostJsonParser.java
When attempting to use `rank:ndcg` as an objective model deployment failed unexpectedly, stating that the objective was invalid.
As per the [XGBoost docs](https://github.com/dmlc/xgboost/blob/1094d6015df7be6f5829e53a4c257f3481b43ee5/doc/parameter.rst#parameters-for-learning-to-rank-rank-ndcg-rank-map-rank-pairwise) `rank:ndcg` and `rank:map` are valid objectives, but are currently rejected by the parser.
This change resolves this by extending the list of objectives which map to the no-op normalizer, allowing the models to be parsed and used by the plugin.
> Add rank:ndcg and rank:map as valid objectives

- src/javaRestTest/java/com/o19s/es/ltr/NodeSettingsIT.java
- src/javaRestTest/java/com/o19s/es/ltr/logging/LoggingIT.java
- src/javaRestTest/java/com/o19s/es/ltr/query/StoredLtrQueryIT.java
- src/main/java/com/o19s/es/ltr/query/RankerQuery.java
- src/main/java/com/o19s/es/ltr/ranker/ArrayFeatureVector.java
- src/main/java/com/o19s/es/ltr/ranker/LogLtrRanker.java
- src/main/java/com/o19s/es/ltr/ranker/LtrRanker.java
- src/main/java/com/o19s/es/ltr/ranker/SparseFeatureVector.java
- src/main/java/com/o19s/es/ltr/ranker/SparseLtrRanker.java
- src/main/java/com/o19s/es/ltr/ranker/dectree/NaiveAdditiveDecisionTree.java
- src/main/java/com/o19s/es/ltr/ranker/ranklib/DenseProgramaticDataPoint.java
- src/test/java/com/o19s/es/ltr/ranker/DenseFeatureVectorTests.java
- src/test/java/com/o19s/es/ltr/ranker/SparseFeatureVectorTests.java
- src/test/java/com/o19s/es/ltr/ranker/dectree/NaiveAdditiveDecisionTreeTests.java
- src/test/java/com/o19s/es/ltr/ranker/parser/XGBoostJsonParserTests.java
This PR attempts to implement support for missing values with XGBoost (https://github.com/o19s/elasticsearch-learning-to-rank/issues/481). 
The main logic change pertains to the initialization of the FeatureVector. As of now, the DenseFeatureVector has a default value of 0.0, and feature scores are filled in with actual values only when they are present. Effectively, features which are missing are given a value of 0.0. This happens "upstream," and by the time XGBoost model (NaiveAdditiveDecisionTree) is invoked, there is no longer any missing feature value.
The implementation here adds a new class called SparseFeatureVector that gives features a default value of Float.NaN, enabling XGBoost model to actually follow branches where the feature is missing.
> Issue 481 - implement support for missing values with XGBoost

- README.md
Noticed a broken link for the Berlin Buzzwords talk while reading the README. It seems the URL redirects to a 2024 subdomain which results in a 404 page. Figured I'd post a quick PR to fix the link (assuming I found the correct URL).
> Update README.md - Fix Broken Berlin Buzzwords URL

- gradle.properties
- src/javaRestTest/java/com/o19s/es/ltr/action/BaseIntegrationTest.java
- src/javaRestTest/java/com/o19s/es/ltr/logging/LoggingIT.java
- src/javaRestTest/java/com/o19s/es/ltr/query/StoredLtrQueryIT.java
- src/main/java/com/o19s/es/explore/ExplorerQuery.java
- src/main/java/com/o19s/es/explore/PostingsExplorerQuery.java
- src/main/java/com/o19s/es/ltr/LtrQueryParserPlugin.java
- src/main/java/com/o19s/es/ltr/action/AddFeaturesToSetAction.java
- src/main/java/com/o19s/es/ltr/action/CachesStatsAction.java
- src/main/java/com/o19s/es/ltr/action/ClearCachesAction.java
- src/main/java/com/o19s/es/ltr/action/CreateModelFromSetAction.java
- src/main/java/com/o19s/es/ltr/action/FeatureStoreAction.java
- src/main/java/com/o19s/es/ltr/action/LTRStatsAction.java
- src/main/java/com/o19s/es/ltr/action/ListStoresAction.java
- src/main/java/com/o19s/es/ltr/action/TransportAddFeatureToSetAction.java
- src/main/java/com/o19s/es/ltr/action/TransportCacheStatsAction.java
- src/main/java/com/o19s/es/ltr/action/TransportClearCachesAction.java
- src/main/java/com/o19s/es/ltr/action/TransportCreateModelFromSetAction.java
- src/main/java/com/o19s/es/ltr/action/TransportFeatureStoreAction.java
- src/main/java/com/o19s/es/ltr/action/TransportLTRStatsAction.java
- src/main/java/com/o19s/es/ltr/action/TransportListStoresAction.java
- src/main/java/com/o19s/es/ltr/feature/FeatureValidation.java
- src/main/java/com/o19s/es/ltr/feature/store/ScriptFeature.java
- src/main/java/com/o19s/es/ltr/feature/store/index/IndexFeatureStore.java
- src/main/java/com/o19s/es/ltr/query/StoredLtrQueryBuilder.java
- src/main/java/com/o19s/es/ltr/rest/RestSearchStoreElements.java
- src/main/java/com/o19s/es/ltr/stats/suppliers/StoreStatsSupplier.java
- src/main/java/com/o19s/es/termstat/TermStatQuery.java
- src/test/java/com/o19s/es/ltr/ShardStatsIT.java
- src/test/java/com/o19s/es/ltr/logging/LoggingFetchSubPhaseTests.java
The plugin would no longer build for newer ES versions. I've worked through the errors and test failures to fix that. Changes included in this PR allow a clean `./gradlew clean check` build for Elasticsearch 8.14.0 (except for flakiness described in https://github.com/o19s/elasticsearch-learning-to-rank/issues/483).
All changes in this PR were made only to facilitate the ES version bump. Here's the list of upstream changes that necessitated changing code:
- https://github.com/elastic/elasticsearch/pull/102354
- https://github.com/elastic/elasticsearch/pull/102800
- https://github.com/apache/lucene/pull/12183
- https://github.com/elastic/elasticsearch/pull/104650
- https://github.com/elastic/elasticsearch/pull/104645
- https://github.com/elastic/elasticsearch/pull/100239 which was a …
> Upgrade to Elasticsearch 8.14.0

- gradle.properties
We're looking into usage of this plugin but we'd like to install a matching Version on our Clusters.
> Update es7_17_X to Elasticsearch 7.17.11

- .github/workflows/release.yml
- build.gradle
- publish/build.gradle
Trying to resolve publishing errors.
Reference:
https://community.sonatype.com/t/401-content-access-is-protected-by-token-authentication-failure-while-performing-maven-release/12741/6
> Add Sonatype user access token information to publish process

- gradle.properties
- src/main/java/com/o19s/es/ltr/action/CachesStatsAction.java
- src/main/java/com/o19s/es/ltr/action/ClearCachesAction.java
- src/main/java/com/o19s/es/ltr/action/LTRStatsAction.java
- src/main/java/com/o19s/es/ltr/action/ListStoresAction.java
- src/main/java/com/o19s/es/ltr/action/TransportClearCachesAction.java
- src/main/java/com/o19s/es/ltr/rest/RestLTRStats.java
- src/test/java/com/o19s/es/ltr/logging/LoggingFetchSubPhaseTests.java
bumps dependencies to elasticsearch 8.15.2
despite the LoggingIT flaky test, everything else looks smooth
> chore: bumps to elasticsearch 8.15.2

- gradle.properties
Update to ES version 8.17.3 because of the kibana vunerability.
- https://thehackernews.com/2025/03/elastic-releases-urgent-fix-for.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.17.3.html
> update to ES version 8.17.3
